version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx_home/conf.d/:/etc/nginx/conf.d/
      - ./nginx_home/nginx.conf/:/etc/nginx/nginx.conf
      - ./nginx_home/log/:/var/log/nginx/
      - ./nginx_home/html:/var/www/html/public
    command: /bin/bash -c "nginx -g 'daemon off;'"
    ulimits:
      nproc: 65535
    restart: always
  
  mysql:
    image: mysql:5.7
    container_name: rocket-mysql
    command: mysqld --user=root --verbose
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: "di"
      MYSQL_PASSWORD: "di@2020!"
      MYSQL_ROOT_PASSWORD: "di@2020!"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  ssdb:
    image: wendal/ssdb:latest
    container_name: rocket-ssdb
    ports:
      - "8888:8888"
    volumes:
      - ./ssdb/ssdb.conf:/etc/ssdb.conf
      - ./ssdb/data:/var/lib/ssdb/data
    restart: always

  user_profile:
    image: registry.gitlab.com/datainsider/user-profile:local
    container_name: rocket-user-profile
    restart: always
    environment:
      NAME: user-profile
      MODE: production
    volumes:
      - ./user-profile/conf:/app/conf
      - ./user-profile/logs:/app/logs
    depends_on:
      - mysql
      - ssdb

  ingestion_service:
    image: registry.gitlab.com/datainsider/ingestion-service:local
    container_name: rocket-ingestion-service
    restart: always
    environment:
      NAME: ingestion-service
      MODE: production
      HTTP_PORT: 8489
      THRIFT_PORT: 8487
    volumes:
      - ./ingestion-service/conf:/app/conf
      - ./ingestion-service/logs:/app/logs
      - ./clickhouse_connection_settings.json:/app/clickhouse_connection_settings.json:ro
    depends_on:
      - mysql
      - ssdb
      - user_profile

  bi_service:
    image: registry.gitlab.com/datainsider/bi-service:local
    container_name: rocket-bi-service
    restart: always
    environment:
      NAME: bi-service
      MODE: production
      HTTP_PORT: 8080
    volumes:
      - ./bi-service/conf:/app/conf
      - ./bi-service/logs:/app/logs
      - ./clickhouse_connection_settings.json:/app/clickhouse_connection_settings.json:ro
    depends_on:
      - mysql
      - ssdb
      - user_profile

  web:
    image: registry.gitlab.com/datainsider/web:local
    container_name: rocket-web
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s

networks:
  default:
    external:
      name: rocket_network
