version: '3.5'
services:
  user-profile:
    image: datainsiderco/caas-service:main
    container_name: rocket-user-profile
    restart: always
    environment:
      NAME: user-profile
      MODE: production
    volumes:
      - ./conf:/app/conf
      - ./logs:/app/logs

networks:
  default:
    external:
      name: rocket_network
