version: "3"

services: 
  mysql:
    image: mysql:5.7
    container_name: rocket-mysql
    command: mysqld --user=root --verbose
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_USER: "di"
      MYSQL_PASSWORD: "di@2020!"
      MYSQL_ROOT_PASSWORD: "di@2020!"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  ssdb:
    image: wendal/ssdb:latest
    container_name: rocket-ssdb
    volumes:
      - ./ssdb/data:/var/lib/ssdb/data
    restart: always

  caas_service:
    image: registry.gitlab.com/datainsider/user-profile:oss
    container_name: rocket-caas-service
    restart: always
    environment:
      NAME: user-profile
      MODE: production
    volumes:
      - ./caas-service/logs:/app/logs
    depends_on:
      - mysql
      - ssdb

  schema_service:
    image: registry.gitlab.com/datainsider/ingestion-service:oss
    container_name: rocket-schema-service
    restart: always
    environment:
      NAME: ingestion-service
      MODE: production
      HTTP_PORT: 8489
      THRIFT_PORT: 8487
    volumes:
      - ./schema-service/logs:/app/logs
      - ./clickhouse_connection_settings.json:/app/clickhouse_connection_settings.json:ro
    depends_on:
      - mysql
      - ssdb
      - caas_service

  bi_service:
    image: registry.gitlab.com/datainsider/bi-service:oss
    container_name: rocket-bi-service
    restart: always
    environment:
      NAME: bi-service
      MODE: production
      HTTP_PORT: 8080
    volumes:
      - ./bi-service/logs:/app/logs
      - ./clickhouse_connection_settings.json:/app/clickhouse_connection_settings.json:ro
    depends_on:
      - mysql
      - ssdb
      - caas_service

  web:
    image: registry.gitlab.com/datainsider/web:1.4.16.1
    container_name: rocket-web
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s

networks:
  default:
    external:
      name: rocket_network
