version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: rocket-mysql
    command: mysqld --user=root --verbose
    restart: always
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_USER: "di"
      MYSQL_PASSWORD: "di@2020!"
      MYSQL_ROOT_PASSWORD: "di@2020!"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  ssdb:
    image: wendal/ssdb:latest
    container_name: rocket-ssdb
    volumes:
      - /var/lib/ssdb/data
    restart: always

  caas_service:
    image: datainsiderco/caas-service:oss
    container_name: rocket-caas-service
    restart: always
    environment:
      NAME: user-profile
      MODE: production
    volumes:
      - /app/logs
    ports:
      - 8580:8580
    depends_on:
      - mysql
      - ssdb

  schema_service:
    image: datainsiderco/schema-service:oss
    container_name: rocket-schema-service
    restart: always
    environment:
      NAME: schema-service
      MODE: production
      HTTP_PORT: 8489
      THRIFT_PORT: 8487
      CLICKHOUSE_HOST: "${CLICKHOUSE_HOST}"
      CLICKHOUSE_HTTP_PORT: "${CLICKHOUSE_HTTP_PORT}"
      CLICKHOUSE_TCP_PORT: "${CLICKHOUSE_TCP_PORT}"
      CLICKHOUSE_USERNAME: "${CLICKHOUSE_USERNAME}"
      CLICKHOUSE_PASSWORD: "${CLICKHOUSE_PASSWORD}"
      CLICKHOUSE_CLUSTER_NAME: "${CLICKHOUSE_CLUSTER_NAME}"
    ports:
      - 8489:8489
    volumes:
      - /app/logs
    depends_on:
      - mysql
      - ssdb
      - caas_service

  bi_service:
    image: datainsiderco/bi-service:oss
    container_name: rocket-bi-service
    restart: always
    ports:
      - 8080:8080
    environment:
      NAME: bi-service
      MODE: production
      HTTP_PORT: 8080
      CLICKHOUSE_HOST: "${CLICKHOUSE_HOST}"
      CLICKHOUSE_HTTP_PORT: "${CLICKHOUSE_HTTP_PORT}"
      CLICKHOUSE_TCP_PORT: "${CLICKHOUSE_TCP_PORT}"
      CLICKHOUSE_USERNAME: "${CLICKHOUSE_USERNAME}"
      CLICKHOUSE_PASSWORD: "${CLICKHOUSE_PASSWORD}"
      CLICKHOUSE_CLUSTER_NAME: "${CLICKHOUSE_CLUSTER_NAME}"
    volumes:
      - /app/logs
    depends_on:
      - mysql
      - ssdb
      - caas_service

  web:
    image: datainsiderco/rocket-bi-web:oss
    container_name: rocket-web
    ports:
      - 5050:8080
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s

networks:
  rocket_network:
