version: '3.7'
services:
  di_web:
    image: datainsiderco/rocket-bi-web:oss
    container_name: di-web
    restart: always
    volumes:
      - ./public/config:/app/config
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s

networks:
  default:
    external:
      name: di_network
