version: '3'
services:
  bi_service:
    image: datainsiderco/bi-service:oss
    container_name: rocket-bi-service
    restart: always
    environment:
      NAME: bi-service
      MODE: production
      HTTP_PORT: 8080
      CLICKHOUSE_HOST: ""
      CLICKHOUSE_HTTP_PORT: 8123
      CLICKHOUSE_TCP_PORT: 9000
      CLICKHOUSE_USERNAME: default
      CLICKHOUSE_PASSWORD: ""
      CLICKHOUSE_CLUSTER_NAME: ""
    ports:
      - "8080:8080"
    volumes:
      - ./conf:/app/conf
      - ./logs:/app/logs

networks:
  default:
    external:
      name: rocket_network
