version: '3'
services:
  bi_service:
    image: registry.gitlab.com/datainsider/bi-service:local
    container_name: rocket-bi-service
    restart: always
    environment:
      NAME: bi-service
      MODE: production
      HTTP_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ./conf:/app/conf
      - ./logs:/app/logs

networks:
  default:
    external:
      name: rocket_network
